/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_jairosierra;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jairo Sierra
 */
public class Principal extends javax.swing.JFrame {

    Administrarmundos ac;
    int cont = 0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jmi_login.setEnabled(false);
        jm_mundos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_usuarios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jp_contra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jd_mundos = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_criaturas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_mundos = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jd_crearcontra = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt_key = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jt_contra = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();
        jd_crear = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jd_crearcri = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jt_nomcria = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jt_energia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jt_anos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jt_region = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jt_vivas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jt_magico = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jd_modmundo = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jt_nombre1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jd_modcri = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jt_nomcria1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jt_energia1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jt_anos1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jt_region1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jt_vivas1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jt_magico1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_login = new javax.swing.JMenu();
        jmi_crear = new javax.swing.JMenuItem();
        jmi_login = new javax.swing.JMenuItem();
        jm_mundos = new javax.swing.JMenu();
        jmi_mundos = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setText("Ingresar");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jp_contra))
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(jt_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton1))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jp_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(86, 86, 86))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel4.setText("Crear Mundo Disco");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Mundos Discos");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Criaturas");

        jl_criaturas.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_criaturas);

        jl_mundos.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_mundos);

        jButton2.setText("Crear Mundo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear Criatura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Modificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Eliminar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Modificar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_mundosLayout = new javax.swing.GroupLayout(jd_mundos.getContentPane());
        jd_mundos.getContentPane().setLayout(jd_mundosLayout);
        jd_mundosLayout.setHorizontalGroup(
            jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundosLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_mundosLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(119, 119, 119))
            .addGroup(jd_mundosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mundosLayout.createSequentialGroup()
                        .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addComponent(jButton8)))
                    .addGroup(jd_mundosLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(jd_mundosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jd_mundosLayout.setVerticalGroup(
            jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mundosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(41, 41, 41)
                .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(8, 8, 8)
                .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_mundosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mundosLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9))
                    .addGroup(jd_mundosLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addGap(28, 28, 28))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Crear Contraseña");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Key");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel9.setText("Contraseña");

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jButton10.setText("Crear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearcontraLayout = new javax.swing.GroupLayout(jd_crearcontra.getContentPane());
        jd_crearcontra.getContentPane().setLayout(jd_crearcontraLayout);
        jd_crearcontraLayout.setHorizontalGroup(
            jd_crearcontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcontraLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jd_crearcontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(jd_crearcontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jt_key, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jd_crearcontraLayout.setVerticalGroup(
            jd_crearcontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcontraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(jd_crearcontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jd_crearcontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(87, 87, 87))
        );

        jLabel5.setText("Crear Mundo");

        jLabel6.setText("Nombre de la tortuga");

        jButton5.setText("Crear");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)
                        .addGap(83, 83, 83)
                        .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jLabel5))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(77, 77, 77))
        );

        jLabel12.setText("Crear Criatura");

        jLabel13.setText("Nombre de la criatura");

        jLabel14.setText("Cantidad de la energia vital ");

        jLabel15.setText("Numero maximo de años");

        jLabel16.setText("Nombre de la region");

        jLabel17.setText("Cantidad de vivas de esa especie");

        jLabel18.setText("Objeto Magico");

        jButton6.setText("Crear");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearcriLayout = new javax.swing.GroupLayout(jd_crearcri.getContentPane());
        jd_crearcri.getContentPane().setLayout(jd_crearcriLayout);
        jd_crearcriLayout.setHorizontalGroup(
            jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcriLayout.createSequentialGroup()
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearcriLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(22, 22, 22)
                        .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nomcria)
                            .addComponent(jt_energia)
                            .addComponent(jt_anos)
                            .addComponent(jt_region)
                            .addComponent(jt_vivas)
                            .addComponent(jt_magico, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                    .addGroup(jd_crearcriLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jLabel12))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jd_crearcriLayout.setVerticalGroup(
            jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(45, 45, 45)
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_nomcria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jt_energia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jt_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jt_vivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_crearcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_magico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(21, 21, 21))
        );

        jLabel19.setText("Crear Mundo");

        jLabel20.setText("Nombre de la tortuga");

        jButton11.setText("Modificar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modmundoLayout = new javax.swing.GroupLayout(jd_modmundo.getContentPane());
        jd_modmundo.getContentPane().setLayout(jd_modmundoLayout);
        jd_modmundoLayout.setHorizontalGroup(
            jd_modmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modmundoLayout.createSequentialGroup()
                .addGroup(jd_modmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modmundoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel20)
                        .addGap(83, 83, 83)
                        .addComponent(jt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modmundoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jd_modmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jButton11))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jd_modmundoLayout.setVerticalGroup(
            jd_modmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modmundoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel19)
                .addGap(63, 63, 63)
                .addGroup(jd_modmundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(77, 77, 77))
        );

        jLabel21.setText("Modificar Criatura");

        jLabel22.setText("Nombre de la criatura");

        jLabel23.setText("Cantidad de la energia vital ");

        jLabel24.setText("Numero maximo de años");

        jLabel25.setText("Nombre de la region");

        jLabel26.setText("Cantidad de vivas de esa especie");

        jLabel27.setText("Objeto Magico");

        jButton12.setText("Modificar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modcriLayout = new javax.swing.GroupLayout(jd_modcri.getContentPane());
        jd_modcri.getContentPane().setLayout(jd_modcriLayout);
        jd_modcriLayout.setHorizontalGroup(
            jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modcriLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jButton12))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modcriLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27))
                    .addGap(22, 22, 22)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jt_nomcria1)
                        .addComponent(jt_energia1)
                        .addComponent(jt_anos1)
                        .addComponent(jt_region1)
                        .addComponent(jt_vivas1)
                        .addComponent(jt_magico1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addContainerGap(113, Short.MAX_VALUE)))
        );
        jd_modcriLayout.setVerticalGroup(
            jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modcriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
            .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modcriLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(jt_nomcria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jt_energia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jt_anos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jt_region1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(41, 41, 41)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jt_vivas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jd_modcriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_magico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addContainerGap(63, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_login.setText("Login");

        jmi_crear.setText("Crear Contraseña");
        jmi_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearActionPerformed(evt);
            }
        });
        jm_login.add(jmi_crear);

        jmi_login.setText("Ingresar");
        jmi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_loginActionPerformed(evt);
            }
        });
        jm_login.add(jmi_login);

        jMenuBar1.add(jm_login);

        jm_mundos.setText("Mundos Disco");

        jmi_mundos.setText("Mundos");
        jmi_mundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mundosActionPerformed(evt);
            }
        });
        jm_mundos.add(jmi_mundos);

        jMenuBar1.add(jm_mundos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jd_crear.setModal(true);
        jd_crear.pack();
        jd_crear.setLocationRelativeTo(this);
        jd_crear.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jl_mundos.getSelectedIndex() >= 0) {
            Indexprivado = jl_criaturas.getSelectedIndex();
            jd_crearcri.setModal(true);
            jd_crearcri.pack();
            jd_crearcri.setLocationRelativeTo(this);
            jd_crearcri.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un mundo para agregarle una criatura!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try {
            String nombre;
            String cantidad;
            String anos;
            String region;
            int vivas;
            nombre = jt_nomcria.getText();
            cantidad = jt_energia.getText();
            anos = jt_anos.getText();
            region = jt_region.getText();
            vivas = Integer.parseInt(jt_vivas.getText());
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().add(new Criaturas(nombre, cantidad, anos, region, vivas));
            ac.escribirarchivo();
            ac.cargararchivo();
            DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
            for (int i = 0; i < ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().size(); i++) {
                modelo.addElement(ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(i));
                jl_criaturas.setModel(modelo);
            }
            jt_nomcria.setText("");
            jt_energia.setText("");
            jt_anos.setText("");
            jt_region.setText("");
            jt_vivas.setText("");
            jd_crearcri.dispose();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(jd_crearcri, "Hay errores en los datos!! Corrija!!");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            if (jl_mundos.getSelectedIndex() >= 0) {
                DefaultListModel modelo=(DefaultListModel)jl_mundos.getModel();      
        modelo.remove(jl_mundos.getSelectedIndex());
        jl_mundos.setModel(modelo);
        try {
            ac.cargararchivo();
            ac.getListamundos().remove(jl_mundos.getSelectedIndex()+1);
            ac.escribirarchivo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar a un mundo!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
        DefaultListModel modelo=(DefaultListModel)jl_criaturas.getModel();
        modelo.remove(jl_criaturas.getSelectedIndex());
        try {
        ac.cargararchivo();
        ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().remove(jl_criaturas.getSelectedIndex());
        ac.escribirarchivo();
        }
        catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jl_mundos.getSelectedIndex() >= 0) {
            String nombre = ((Mundo_Disco)ac.getListamundos().get(jl_mundos.getSelectedIndex())).getNombre();
            jt_nombre1.setText(nombre);
            jd_modmundo.setModal(true);
            jd_modmundo.pack();
            jd_modmundo.setLocationRelativeTo(this);
            jd_modmundo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un mundo!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
            if (jl_mundos.getSelectedIndex() >= 0) {
                String nombre = jt_nombre1.getText();
                ac.getListamundos().get(jl_mundos.getSelectedIndex()).setNombre(nombre);
                ac.cargararchivo();
                ac.escribirarchivo();
                jt_nombre1.setText("");
                DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
                modelo.clear();
                for (int i = 0; i < ac.getListamundos().size(); i++) {
                    modelo.addElement(ac.getListamundos().get(i));
                }
                jl_mundos.setModel(modelo);
                jd_modmundo.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar a un mundo!");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(jd_modmundo, "Algun dato es incorrecto! Corrija los errores!");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (jl_criaturas.getSelectedIndex() >= 0 && jl_mundos.getSelectedIndex() >= 0) {
            String vivas = Integer.toString(((Criaturas)ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex())).getVivas());
            jt_energia1.setText(((Criaturas)ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex())).getCantidad());
            jt_anos1.setText(((Criaturas)ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex())).getAnos());
            jt_region1.setText(((Criaturas)ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex())).getRegion());
            jt_vivas.setText(vivas);
            jt_nomcria1.setText(((Criaturas)ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex())).getNombre());
            cont++;
            jd_modcri.setModal(true);
            jd_modcri.pack();
            jd_modcri.setLocationRelativeTo(this);
            jd_modcri.setVisible(true);
            jt_nomcria.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un mundo y una criatura!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{
        if (jl_mundos.getSelectedIndex() >= 0 && jl_criaturas.getSelectedIndex() >= 0) {
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex()).setCantidad(jt_energia1.getText());
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex()).setAnos(jt_anos1.getText());
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex()).setRegion(jt_region1.getText());
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex()).setVivas(Integer.parseInt(jt_vivas1.getText()));
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex()).setNombre(jt_nomcria1.getText());
            ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(jl_criaturas.getSelectedIndex()).getObjetos().add(jt_magico1.getText());
            jt_energia1.setText("");
            jt_nomcria1.setText("");
            jt_anos1.setText("");
            jt_region1.setText("");
            jt_vivas1.setText("");
            jt_magico1.setText("");
            ac.escribirarchivo();
            ac.cargararchivo();
            DefaultListModel modelo = (DefaultListModel) jl_criaturas.getModel();
            modelo.clear();
            for (int i = 0; i < ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().size(); i++) {
                modelo.addElement(ac.getListamundos().get(jl_mundos.getSelectedIndex()).getCriaturas().get(i));
            }
            jl_criaturas.setModel(modelo);
            jd_modcri.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar a un mundo y una criatura!");
        }
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(jd_modcri, "Algun dato es incorrecto! Corrija los errores!");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jmi_mundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mundosActionPerformed
        // TODO add your handling code here:
        jd_mundos.setModal(true);
            jd_mundos.pack();
            jd_mundos.setLocationRelativeTo(this);
            jd_mundos.setVisible(true);
    }//GEN-LAST:event_jmi_mundosActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{                                          
            // TODO add your handling code here:
            String contra = jt_contra.getText(),nueva="";
            int tem,n,key=Integer.parseInt(jt_key.getText());
            char letra;
            for (int i = 0; i < contra.length(); i++) {
                tem = contra.codePointAt(i);
                if(tem==122){
                    tem=65;
                }
                if(tem==90){
                    tem=97;
                }
                n=tem+key;
                letra = (char)n;
                nueva += letra;
            }
            File archivo = new File("./credenciales.txt");
            FileWriter fw = null;
            BufferedWriter bw = null;
            try{
                fw = new FileWriter(archivo,false);
                bw = new BufferedWriter(fw);
                bw.write(usuario+";");
                bw.write(Integer.toString(key)+";");
                bw.write(nueva+";");
                bw.flush();
            }
            catch(Exception e){
                
            }
            bw.close();
            fw.close();
            
        }
        catch(IOException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        jmi_login.setEnabled(true);
        jd_crearcontra.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            String nombre = jt_nombre.getText();
            ac = new Administrarmundos("./Mundos/" + nombre + ".txt");
            ac.getListamundos().add(new Mundo_Disco(nombre));
            ac.escribirarchivo();
            jt_nombre.setText("");
            ac.cargararchivo();
            DefaultListModel modelo = (DefaultListModel) jl_mundos.getModel();
            for (int i = 0; i < ac.getListamundos().size(); i++) {
                modelo.addElement(ac.getListamundos().get(i));
            }
            jl_mundos.setModel(modelo);
            jd_crear.dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(jd_crear, "Algun dato es incorrecto! Corrija los errores!");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
        String contrasena="";
        String usuario="";
        int key =0;
        Scanner sc = null;
        File archivo;
        try{
            archivo = new File("./Credenciales.txt");
            sc = new Scanner(archivo);
            sc.useDelimiter(";");
            usuario = sc.next();
            contrasena = sc.next();
            key = sc.nextInt();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        contrasena = decifrar(contrasena,key);
        if(jt_usuarios.getText().equals(usuario) && jp_contra.getText().equals(contrasena)){
            jm_mundos.setEnabled(true);
            jmi_crear.setEnabled(false);
        }
        sc.close();
        }catch(Exception e){
            
        }
        jd_login.dispose();
        jm_mundos.setEnabled(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearActionPerformed
        // TODO add your handling code here:
        jd_crearcontra.setModal(true);
            jd_crearcontra.pack();
            jd_crearcontra.setLocationRelativeTo(this);
            jd_crearcontra.setVisible(true);
    }//GEN-LAST:event_jmi_crearActionPerformed

    private void jmi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_loginActionPerformed
        // TODO add your handling code here:
        jd_login.setModal(true);
            jd_login.pack();
            jd_login.setLocationRelativeTo(this);
            jd_login.setVisible(true);
    }//GEN-LAST:event_jmi_loginActionPerformed
public String decifrar(String contra,int key){
    String cifrar="";
    int num;
    for (int i = 0; i < contra.length(); i++) {
        num = contra.codePointAt(i);
        if(num==122){
            num=65;
        }
        if(num==90){
            num=97;
        }
        char tem = (char)(num-key);
        cifrar+=tem;
    }
    return cifrar;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_crearcontra;
    private javax.swing.JDialog jd_crearcri;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_modcri;
    private javax.swing.JDialog jd_modmundo;
    private javax.swing.JDialog jd_mundos;
    private javax.swing.JList<String> jl_criaturas;
    private javax.swing.JList<String> jl_mundos;
    private javax.swing.JMenu jm_login;
    private javax.swing.JMenu jm_mundos;
    private javax.swing.JMenuItem jmi_crear;
    private javax.swing.JMenuItem jmi_login;
    private javax.swing.JMenuItem jmi_mundos;
    private javax.swing.JPasswordField jp_contra;
    private javax.swing.JTextField jt_anos;
    private javax.swing.JTextField jt_anos1;
    private javax.swing.JPasswordField jt_contra;
    private javax.swing.JTextField jt_energia;
    private javax.swing.JTextField jt_energia1;
    private javax.swing.JTextField jt_key;
    private javax.swing.JTextField jt_magico;
    private javax.swing.JTextField jt_magico1;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombre1;
    private javax.swing.JTextField jt_nomcria;
    private javax.swing.JTextField jt_nomcria1;
    private javax.swing.JTextField jt_region;
    private javax.swing.JTextField jt_region1;
    private javax.swing.JTextField jt_usuarios;
    private javax.swing.JTextField jt_vivas;
    private javax.swing.JTextField jt_vivas1;
    // End of variables declaration//GEN-END:variables
ArrayList<Mundo_Disco> lista = new ArrayList();
    ArrayList<Criaturas> lista2 = new ArrayList();
    private int Indexprivado;
    private String usuario ="xXxGranATuinxXx";
}
